### ISSUE TITLE
Calculating SMB from WINDEROSIONDEPOSITION field

### ISSUE THREAD

**Issue by EricKeenan** [snowpack-model/snowpack#13]
Delta SWE is identical to (MS_HNW - MS_WIND - ET - MS_SNOWPACK_RUNOFF). But is not equal to (pr - WINDEROSIONDEPOSITION - ET - MS_SNOWPACK_RUNOFF)

Based off my understanding of the variables I would expect both expressions to be equal to detla SWE. Do you agree? If so, could the discrepancy be due to a programing error? My impression is that numerical errors arising from explicit snow drift should be encapsulated in delta swe and WINDEROSIONDEPOSITION, and therefore should not explain the difference. 
<img width="564" alt="Screen Shot 2020-10-29 at 4 40 46 PM" src="https://user-images.githubusercontent.com/44210245/97641623-efca3880-1a08-11eb-9982-c33e0cea1754.png">

**Comment by nwever** [comment]
Fixed by commit f36940c4806cf7cd04d4bb94c0e76f243ae523e1
