### ISSUE TITLE
Alpine-3D writes SWE to netCDF, but units are off.

### ISSUE THREAD

**Issue by EricKeenan** [snowpack-model/snowpack#2]
netCDF metadata indicate SWE units are meters liquid water equivalent, but values are around 1000. So I guess they are in mm? 
```
xarray.DataArray'swe'northing: 107easting: 168
1040.2449 1040.1312 1039.4742 1039.2972 1039.1523 ... nan nan nan nan
Coordinates:
time
()
datetime64[ns]
1980-01-09T12:00:00
northing
(northing)
float32
-109000.0 -108000.0 ... -3000.0
easting
(easting)
float32
-1542000.0 ... -1375000.0
Attributes:
standard_name :
lwe_thickness_of_surface_snow_amount
units :
m
```

**Comment by EricKeenan** [comment]
Slightly off-topic from the original issue - but I think it would be nice to add the following information to the netCDF files.

- Grid cell area: Computing integrated quantities, i.e. SMB in Gt. 

- Lat/Lon in WGS-84: Useful for those not familiar with plotting in different coordinate systems.

**Comment by nwever** [comment]
Units for SWE correct as of commit c521202.

**Comment by EricKeenan** [comment]
Great! Closing this issue now.
