### ISSUE TITLE
Calculating SMB for Alpine-3D netCDF output

### ISSUE THREAD

**Issue by EricKeenan** [snowpack-model/snowpack#3]
I'm working on adding surface mass balance (SMB) to `SnowpackInterfaceWorker.cc`

To do so I am adding a new case to `void SnowpackInterfaceWorker::fillGrids(const size_t& ii, const size_t& jj, const CurrentMeteo& meteoPixel, const SnowStation& snowPixel, const SurfaceFluxes& surfaceFlux)`. Does this look roughly right? I'm not farmiliar with tests for negative numbers, float/int, etc in C++. So any help/review would be appreciated!

So far I've tried to account for precipitation, sublimation, and meltwater runoff. I don't quite understand how to add drifting snow erosion... Am I correct that at the moment, SNOWPACK has no drifting snow sublimation term? 

```
case SnGrids::SMB:
   value = meteoPixel.psum  - (surfaceFlux.mass[SurfaceFluxes::MS_SUBLIMATION] / snowPixel.cos_sl) - surfaceFlux.mass[SurfaceFluxes::MS_SNOWPACK_RUNOFF]; break;
```

**Comment by nwever** [comment]
It needs to include surfaceFlux.mass[MS_EVAPORATION] as well. There is not (yet) a snowdrift sublimation term. There is a snow drift term, though (Sdata.mass[SurfaceFluxes::MS_WIND]/cos_sl). Maybe it's also good to use Sdata.mass[SurfaceFluxes::MS_HNW] (for snow) and Sdata.mass[SurfaceFluxes::MS_RAIN] (for rain), instead of PSUM.

**Comment by EricKeenan** [comment]
Thanks for helping me get on track. A few things to still figure out:
1. Still need to determine which variables to divide by cos(slope)
2. Difference between Sdata.mass and surfaceFlux.mass? 
3. Synchronize rates and mass contributions in order to have a consistent SMB variable. 
4. Is the timestep used in accumulated variables (e.g. MS_EVAPORATION) from SNOWPACK or Alpine-3D? 
5. ~~Confirm flux and rate directions (components signs) are correct.~~

```
/*
Calculates Surface Mass Balance (SMB) as a function of snowfall, rain, wind erosion, surface sublimation, 
evaporation, and meltwater runoff. Note that SNOWPACK does not yet account for drifting snow sublimation.

Components: 
	Snow rate: MS_HNW (kg/m2/hr)
	Rain rate: MS_RAIN (kg/m2/hr)
	Wind erosion rate: MS_WIND (kg/m2/hr)
	Sublimation: MS_SUBLIMATION (kg/m2, presumably over the timestep)
	Evaporation: MS_EVAPORATION (kg/m2, presumably over the timestep)
	Meltwater runoff: MS_SNOWPACK_RUNOFF (kg/m2, presumably over the timestep)
*/

case SnGrids::SMB:
   value = Sdata.mass[SurfaceFluxes::MS_HNW]
   + Sdata.mass[SurfaceFluxes::MS_RAIN]
   + Sdata.mass[SurfaceFluxes::MS_WIND]
   + (surfaceFlux.mass[SurfaceFluxes::MS_SUBLIMATION] / snowPixel.cos_sl)
   + (surfaceFlux.mass[SurfaceFluxes::MS_EVAPORATION] / snowPixel.cos_sl)
   - (surfaceFlux.mass[SurfaceFluxes::MS_SNOWPACK_RUNOFF] / snowPixel.cos_sl); break;
```
